add_newline = true
format = '''
[┌\[󰣇\] ](blue)$username[@](white)$hostname$directory
[└─\$ ](blue)'''

[username]
style_user = 'purple bold'
style_root = 'black bold'
format = '[$user]($style)'
show_always = true

[hostname]
style = 'purple bold'
ssh_only = false

[directory]
truncation_length = 5
truncate_to_repo = false

