add_newline = true
format = '''
[┌\[󰣇\] ](blue)$username[@](white)$hostname$directory
[└─\$ ](blue)'''

[username]
style_user = 'purple bold'
style_root = 'black bold'
format = '[$user]($style)'
show_always = true

[hostname]
ssh_only=false
style = 'purple bold'
